// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB6aNATCYQKt8Q0lDp7V7PrAuiMO48-BU',
    appId: '1:459444905390:web:814400ddb556b2525c143f',
    messagingSenderId: '459444905390',
    projectId: 'matharena-a4da1',
    authDomain: 'matharena-a4da1.firebaseapp.com',
    databaseURL: 'https://matharena-a4da1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matharena-a4da1.firebasestorage.app',
    measurementId: 'G-W00KQFTNVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6aNATCYQKt8Q0lDp7V7PrAuiMO48-BU',
    appId: '1:459444905390:android:PLACEHOLDER',
    messagingSenderId: '459444905390',
    projectId: 'matharena-a4da1',
    databaseURL: 'https://matharena-a4da1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matharena-a4da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_APP_ID:ios:YOUR_IOS_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'https://YOUR_PROJECT_ID-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.matharena.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_APP_ID:ios:YOUR_IOS_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'https://YOUR_PROJECT_ID-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.matharena.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB6aNATCYQKt8Q0lDp7V7PrAuiMO48-BU',
    appId: '1:459444905390:web:814400ddb556b2525c143f',
    messagingSenderId: '459444905390',
    projectId: 'matharena-a4da1',
    authDomain: 'matharena-a4da1.firebaseapp.com',
    databaseURL: 'https://matharena-a4da1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matharena-a4da1.firebasestorage.app',
  );
}
